# Periodic example

In [1]:
import numpy as np
import plotly.graph_objects as go

x_periodic = np.linspace(0, 10, 1000)
y_periodic = np.cos(5 * x_periodic)

fig = go.Figure(data=go.Scatter(x=x_periodic, y=y_periodic))
fig.update_layout(xaxis_title="Timestamp", yaxis_title="Amplitude")
fig.show()

In [2]:
from gtda.time_series import SingleTakensEmbedding

embedding_dimension_periodic = 2
embedding_time_delay_periodic = 8
stride = 10

embedder_periodic = SingleTakensEmbedding(
    parameters_type="fixed",
    n_jobs=2,
    time_delay=embedding_time_delay_periodic,
    dimension=embedding_dimension_periodic,
    stride=stride,
)

y_periodic_embedded = embedder_periodic.fit_transform(y_periodic)
print(f"Shape of embedded time series: {y_periodic_embedded.shape}")

Shape of embedded time series: (100, 2)


In [3]:
from gtda.plotting import plot_point_cloud

plot_point_cloud(y_periodic_embedded)

# Non-Periodic example

In [4]:
x_nonperiodic = np.linspace(0, 5000, 1000)
y_nonperiodic = np.cos(x_nonperiodic) + np.cos(np.pi * x_nonperiodic)

fig = go.Figure(data=go.Scatter(x=x_nonperiodic, y=y_nonperiodic))
fig.update_layout(xaxis_title="Timestamp", yaxis_title="Amplitude")
fig.show()

In [9]:
y_nonperiodic

array([ 2.00000000e+00, -7.11418352e-01,  1.65921646e-01, -1.76825364e+00,
        1.38774710e+00, -2.70694540e-03,  1.17940114e+00, -1.88208819e+00,
        2.95869024e-01, -5.03530610e-01,  1.96454778e+00, -9.07972569e-01,
        4.98520979e-02, -1.59420476e+00,  1.55345161e+00, -2.40745673e-02,
        9.37992723e-01, -1.93033912e+00,  4.33526836e-01, -2.93707541e-01,
        1.85956419e+00, -1.08378718e+00, -4.73454833e-02, -1.36756328e+00,
        1.66837620e+00, -6.52916642e-02,  6.74099800e-01, -1.91014053e+00,
        5.71843494e-01, -9.09102063e-02,  1.68911148e+00, -1.22989093e+00,
       -1.22071931e-01, -1.09786157e+00,  1.72621098e+00, -1.23405212e-01,
        3.98824666e-01, -1.82127802e+00,  7.03226192e-01,  9.67335045e-02,
        1.45977285e+00, -1.33818300e+00, -1.72267376e-01, -7.96125237e-01,
        1.72279093e+00, -1.94189679e-01,  1.23307739e-01, -1.66622694e+00,
        8.19921493e-01,  2.62273860e-01,  1.18038007e+00, -1.40184066e+00,
       -1.97472064e-01, -

In [5]:
embedding_dimension_nonperiodic = 3
embedding_time_delay_nonperiodic = 16
stride = 3

embedder_nonperiodic = SingleTakensEmbedding(
    parameters_type="fixed",
    n_jobs=2,
    time_delay=embedding_time_delay_nonperiodic,
    dimension=embedding_dimension_nonperiodic,
    stride=stride,
)

y_nonperiodic_embedded = embedder_nonperiodic.fit_transform(y_nonperiodic)

plot_point_cloud(y_nonperiodic_embedded)

# Persistence Diagrams 

In [6]:
y_periodic_embedded = y_periodic_embedded[None, :, :]
y_nonperiodic_embedded = y_nonperiodic_embedded[None, :, :]

In [10]:
y_nonperiodic_embedded

array([[[-7.11418352e-01, -1.93033912e+00, -1.09786157e+00],
        [ 1.38774710e+00,  1.85956419e+00,  3.98824666e-01],
        [-1.88208819e+00, -1.36756328e+00,  9.67335045e-02],
        [ 1.96454778e+00,  6.74099800e-01, -1.72267376e-01],
        [-1.59420476e+00, -9.09102063e-02, -1.94189679e-01],
        [ 9.37992723e-01, -1.22071931e-01,  8.19921493e-01],
        [-2.93707541e-01, -1.23405212e-01, -1.40184066e+00],
        [-4.73454833e-02,  7.03226192e-01,  1.65632524e+00],
        [-6.52916642e-02, -1.33818300e+00, -1.45007828e+00],
        [ 5.71843494e-01,  1.72279093e+00,  8.61648859e-01],
        [-1.22989093e+00, -1.66622694e+00, -1.45236788e-01],
        [ 1.72621098e+00,  1.18038007e+00, -3.86523299e-01],
        [-1.82127802e+00, -4.74398982e-01,  5.06730655e-01],
        [ 1.45977285e+00, -1.41748338e-01, -1.78839585e-01],
        [-7.96125237e-01,  4.00218016e-01, -4.26525254e-01],
        [ 1.23307739e-01, -1.98801700e-01,  1.01031565e+00],
        [ 2.62273860e-01

In [7]:
from gtda.homology import VietorisRipsPersistence

# 0 - connected components, 1 - loops, 2 - voids
homology_dimensions = [0, 1, 2]

periodic_persistence = VietorisRipsPersistence(
    homology_dimensions=homology_dimensions, n_jobs=6
)
print("Persistence diagram for periodic signal")
periodic_persistence.fit_transform_plot(y_periodic_embedded)

Persistence diagram for periodic signal


array([[[0.        , 0.01523799, 0.        ],
        [0.        , 0.01531223, 0.        ],
        [0.        , 0.01564779, 0.        ],
        [0.        , 0.01635941, 0.        ],
        [0.        , 0.01706192, 0.        ],
        [0.        , 0.01733322, 0.        ],
        [0.        , 0.01917304, 0.        ],
        [0.        , 0.01952692, 0.        ],
        [0.        , 0.0206098 , 0.        ],
        [0.        , 0.02099742, 0.        ],
        [0.        , 0.02105048, 0.        ],
        [0.        , 0.02216656, 0.        ],
        [0.        , 0.0233861 , 0.        ],
        [0.        , 0.02381447, 0.        ],
        [0.        , 0.0263881 , 0.        ],
        [0.        , 0.02684042, 0.        ],
        [0.        , 0.0281714 , 0.        ],
        [0.        , 0.02863201, 0.        ],
        [0.        , 0.02901379, 0.        ],
        [0.        , 0.0313423 , 0.        ],
        [0.        , 0.03181043, 0.        ],
        [0.        , 0.03285298, 0

In [8]:
nonperiodic_persistence = VietorisRipsPersistence(
    homology_dimensions=homology_dimensions, n_jobs=6
)
print("Persistence diagram for nonperiodic signal")
nonperiodic_persistence.fit_transform_plot(y_nonperiodic_embedded);

Persistence diagram for nonperiodic signal


What can we conclude from these diagrams? The first thing that stands out is the different types of homology dimensions that are most persistent. In the periodic case we see a single point associated with 1-dimensional persistent homology, namely a loop! On the other hand, the non-periodic signal has revealed two points associated with 2-dimensional persistent homology, namely voids. These clear differences in topology make the time delay embedding technique especially powerful at class
ifying different time series.
